name: Selenium Tests Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Permite iniciar manualmente

jobs:
  run-tests:
    runs-on: ubuntu-latest



    steps:
      - name: ✅ Checkout repository
        uses: actions/checkout@v4

      - name: ✅ Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: ✅ Set up Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: ✅ Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: ✅ Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'



      - name: ✅ Run regression tests with Chrome
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/Runners/regression.xml


      - name: ✅ Run smoke tests with Chrome
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/Runners/smoke.xml


      - name: ✅ Upload Extent Report
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: test-output/extentReport.html
